# Generated by Django 3.0.2 on 2020-01-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Project duration')),
                ('active', models.BooleanField(default=False, verbose_name='Is project ative')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full names')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('facebook', models.CharField(max_length=200, verbose_name='Facebook profile')),
                ('linkedin', models.CharField(max_length=200, verbose_name='LinkedIn profile')),
                ('github', models.CharField(max_length=200, verbose_name='Github profile')),
                ('tweeter', models.CharField(max_length=200, verbose_name='Tweeter profile')),
                ('image', models.ImageField(upload_to='', verbose_name='Profile picture')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full names')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('image', models.ImageField(upload_to='', verbose_name='Profile picture')),
            ],
        ),
    ]
