# Generated by Django 3.0.2 on 2020-01-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se_dmc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.CharField(max_length=200)),
            ],
        ),
    ]
