# Generated by Django 3.0.2 on 2020-02-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('se_dmc', '0003_auto_20200203_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
