# Generated by Django 3.0.2 on 2020-02-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('se_dmc', '0006_contact1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact1',
        ),
    ]
