from .blog import Blog
from .home_view import HomeView
from .services import Services
from .work import Work
from .about import About
from .contact import Contact,contact
from .policy import Policies
from .document import Documents, document_list
from .tshilo_dikotla import TshiloDikotla
from .cancer import Cancer
from .microbiome import Microbiome
from .lis import Lis
from .eit import Eit
from .bcpp import Bcpp
from .ambition import Ambition
from .redcap import RedCap
from .odk import OpenDataKit
from .edc import ElectronicDataCapture
from .dataverse import DataVerse
